### ISSUE TITLE
关于gpu运行的问题

### ISSUE THREAD

**Issue by LeightonQian417** [Treedy2020/TransNet#1]
我电脑是1080ti的gpu，windows系统，我发现我在用gpu跑这个程序的时候由于cuda版本问题只能安装pytorch1.8.0 ，1.8里面的torch.fft函数和这里源代码的最低版本1.2不太一样，导致我没办法计算ρ的值，代码一直报错，因为看到您的代码里面没有修改这一部分，想问下您是怎么顺利运行的？或许是因为系统原因吗？
![image](https://user-images.githubusercontent.com/34114370/156883482-44ea5f76-3916-4791-911f-3c281ea237dd.png)
这个是1.8.0的fft函数
![image](https://user-images.githubusercontent.com/34114370/156883545-2b83722f-64fa-4e5b-9e57-039335d93152.png)
这个是1.2.0的fft函数
![image](https://user-images.githubusercontent.com/34114370/156883640-9f9f1705-c9cc-4624-bf01-516e9a31b1ab.png)
因为两者输入完全不一样，代码出现了报错

**Comment by Treedy2020** [comment]
确实是torch的原因，具体的说，是因为在旧版本中，复数的tensor是采用同样shape的实数来保存虚部和实部，而新的torch.fft.fft则以 a+bj 的形式输入复数tensor。
我尝试过用新版本的torch.fft.fft修改，虽然能跑起来计算NMSE，但是会出现奇怪的rho的值计算为null。我还没有解决这个问题，因此暂时建议采用1.2.0 -1.6之间的Pytorch版本（这之间的版本没有丢弃torch.fft），我自身采用2080Ti进行训练开源，在Windows和Linux上都用CUDA 10以上的Pytorch 1.5版本，都是可以跑的^_^。

**Comment by LeightonQian417** [comment]
好的，感谢，前些时间我使用1.4.0版本跑通了^_^
